version: '3'
services:
  web:
    build: .
    image: docker-sample-rails:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "6123:3000"
    env_file:
      - development.env
